name: otsu_environment
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - xarray
  - rioxarray
  - s3fs
  - gcsfs
  - folium
  - ipyleaflet
  - eoreader
  - eosets
